-- =====================================================================
-- Stock Market Historical Data Analysis - MS SQL Server
-- Part 2: Data Loading (BULK INSERT)
-- =====================================================================

USE StockMarketAnalysis;
GO

-- =====================================================================
-- BULK INSERT Instructions
-- =====================================================================
-- NOTE: This script uses BULK INSERT which requires file system access.
-- 
-- Alternative approaches if BULK INSERT doesn't work:
-- 1. Use SQL Server Import/Export Wizard (GUI)
-- 2. Use bcp utility from command line
-- 3. Use INSERT statements generated by Python/other tools
-- 4. Use SSMS "Import Flat File" feature (newer versions)
-- 
-- Make sure the combined_stock_data.csv file is accessible to SQL Server
-- =====================================================================

-- Option 1: BULK INSERT (fastest for large datasets)
-- Update the file path to match your system
BULK INSERT dbo.StockPrices
FROM 'C:\path\to\combined_stock_data.csv'  -- Update this path!
WITH (
    FIRSTROW = 2,           -- Skip header row
    FIELDTERMINATOR = ',',  -- CSV delimiter
    ROWTERMINATOR = '\n',   -- Line terminator
    TABLOCK,                -- Table lock for better performance
    ERRORFILE = 'C:\path\to\bulk_insert_errors.log'  -- Error log
);
GO

-- Verify data loaded
SELECT 
    '✓ Data Loading Complete!' AS Status,
    COUNT(*) AS TotalRecords,
    COUNT(DISTINCT Ticker) AS UniqueStocks,
    MIN(Date) AS EarliestDate,
    MAX(Date) AS LatestDate
FROM dbo.StockPrices;
GO

-- Check records by ticker
SELECT 
    Ticker,
    COUNT(*) AS Records,
    MIN(Date) AS FirstDate,
    MAX(Date) AS LastDate,
    DATEDIFF(MONTH, MIN(Date), MAX(Date)) AS MonthsOfData
FROM dbo.StockPrices
GROUP BY Ticker
ORDER BY Ticker;
GO

PRINT '✓ Data loading section completed';
PRINT '  If BULK INSERT failed, use alternative methods listed above';
GO